# Generated by Django 3.2.6 on 2021-09-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210911_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='published',
            field=models.DateField(auto_now_add=True),
        ),
    ]
